### ISSUE TITLE
Update Readme and BaseCalc Docs

### ISSUE THREAD

**Issue by IltonS** [IltonS/calculator#5]
# To-do

* [x] Add BaseCalc readme file
* [x]  Upload social preview image
* [x]  Add readme cover image
* [x]  Add icon to readme
* [x]  Add 'v' to the version in the title
